version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app_deploy/
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 30
      runas: ubuntu
  ApplicationStart:
    - location: server_start.sh
      timeout: 30
      runas: ubuntu
  ApplicationStop:
    - location: server_stop.sh
      timeout: 30
      runas: ubuntu